### ISSUE TITLE
您好，我现在正在学习自定义View正好看到您的文章，看了您的代码以后，有个问题请教。

### ISSUE THREAD

**Issue by mrchenmo** [ChengangFeng/TickView#3]
int width = getMySize((radius + dp2px(mContext, 2.5f) * SCALE_TIMES) * 2, widthMeasureSpec);
        int height = getMySize((radius + dp2px(mContext, 2.5f) * SCALE_TIMES) * 2, heightMeasureSpec);

        height = width = Math.max(width, height);

        setMeasuredDimension(width, height);
这段代码的意义是什么？我注释掉以后没有不一样所以想请教您一下。

**Comment by ChengangFeng** [comment]
因为动画的最后一步有个放大的动画，这里的代码是为了防止执行放大动画后，动画会超出控件的范围，所以这样设置

**Comment by ChengangFeng** [comment]
@mrchenmo 因为动画的最后一步有个放大的动画，这里的代码是为了防止执行放大动画后，动画会超出控件的范围，所以这样设置

**Comment by mrchenmo** [comment]
@ChengangFeng 是比如使用固定的宽高的时候，将放大动画限制在设定值以内是这样吗？我来实验一下将宽高设成一个很小的值。

**Comment by ChengangFeng** [comment]
@mrchenmo 恩，是的
